package tech.calaverita.WeeklyLoansReport.entities;

import lombok.Data;

@Data
public class LoanFull {
    private Integer Index;
    private String PrestamoID;
    private String ClienteId;
    private String Nombres;
    private String ApellidoPaterno;
    private String ApellidoMaterno;
    private String Direccion;
    private String NoExterior;
    private String NoInterior;
    private String Colonia;
    private String CodigoPostal;
    private String Municipio;
    private String Estado;
    private String NoDeContrato;
    private String Agente;
    private String Gerencia;
    private Integer Semana;
    private Integer Anio;
    private Integer Plazo;
    private Double MontoOtorgado;
    private Double Cargo;
    private Double TotalAPagar;
    private Double PrimerPago;
    private Double Tarifa;
    private String SaldosMigrados;
    private String WkDescu;
    private Double Descuento;
    private String Porcentaje;
    private String Multas;
    private String WkRefi;
    private String Refin;
    private String Externo;
    private Double Saldo;
    private Double Cobrado;
    private String TipoDeCredito;
    private String Aclaracion;
    private String NombresAval;
    private String ApellidoPaternoAval;
    private String ApellidoMaternoAval;
    private String DireccionAval;
    private String NoExteriorAval;
    private String NoInteriorAval;
    private String ColoniaAval;
    private String CodigoPostalAval;
    private String PoblacionAval;
    private String EstadoAval;
    private String TelefonoAval;
    private String TelefonoCliente;
    private String DiaDePago;
    private String GerenteEnTurno;
    private String Agente2;
    private String Status;
    private String Capturista;
    private String NoServicio;
    private String TipoDeCliente;
    private String IdentificadorCredito;
    private String Seguridad;
    private String Depuracion;
    private String FolioDePagare;
    private String[] fullLine;
    private String fechaPrestamo;
}
